    <div>
        <h1 class="text-5xl font-semibold m-10">Political Systems</h1>
        <h3 class="m-7 text-3xl">
    Soviet Union was Communist, or more specifically, Marxist-Leninist, which is two different ideologies combined, Marxism, and Leninism. Marxism states that history is always a duel between two opposing groups, and eventually whichever one is more freeing will succeed, in feudalism, between the Lords and the Peasants, which eventually moved to Capitalism, the Business Owners against the workers, and he thinks the next common one will be Communism. It also is against Capitalism, due to the Bougeois(The Ruling Class: Rich Employers, Company Owners, etc), continuing to get more and more rich, while the people who work for them(the Proletariat: The rest of the people) are paid unfairly, despite often doing more work; To go with that, it says that people need to build Class Consciousness(understanding of the class system, and that your interests are opposed to the interests of the opposite class) to fix society, and make it more equal. Leninism says that the proletariat are not educated, or patriotic, or similar to be able to fight a bad system, and thus it's better to have a group of only the smart people to make all the decisions for everyone. (Paraphrased from <a class="underline" href="https://yawboadu.substack.com/p/why-is-russia-such-an-asshole-is-d23"> "What is Marxist-Leninism? Heck, what is Marxism?"</a>)
</h3>

        <p class="text-3xl font-normal m-7">
            Under their interpretation of Communism, one party had complete control over the government, and all elections were just for show, as all candidates were directly chosen by the CPSU (Communist Party of the Soviet Union), and there was little to no free speech, up until Glasnost which allowed anyone to run in elections, and gave people free speech.

            Many of the republics didn't like that, and left the union soon after. Lithuania, Georgia, and Latvia were some of the first to remove themselves from the union. People who were more devout to the idea of Communism in the CPSU tried to seize power from Gorbachev, but was unsuccessful, in what is currently known as the August Coup. This hurt the power in the central government, and eventually led to Mikhail Gorbachev giving up all power, and leaving former Soviet Republics to figure out how to govern themselves. The Commonwealth of Indepependent States was formed soon after, of former republics, meant to strengthen trade and peace between them, inspired by the EU, but has not been anywhere near as successful.
        </p>
    </div>